SSID = "mywifi"
PASSWORD = "wifi_pw"
CLIENT = "Cistern"
MQTTHOST = "192.168.0.3"
MQTTUSER = "user"
MQTTPASS = "pass"
UTCOFFSET = "0"
PROBENAME = "Tank_Monitor_"
STATE_TOPIC = "Cistern"
TANK_HEIGHT = 152
#NB: Using a JSN-SR04T with Working range: 25cm-4M, Working frequency: 40KHZ, Detecting angle: 70 degree.
MIN_DISTANCE_TO_TOP_OF_LIQUID = 25
TRIGGER_PIN = 14
ECHO_PIN = 15
SECONDS_BETWEEN_READINGS = 10
EMAIL_ALERT_FLAG = False
EMAIL_SMS_FLAG = False
EMAIL_THRESHOLD = 85
SMS_THRESHOLD = 93
EMAIL_LOGIN_USER = "email.user@yourdomain.com"
EMAIL_LOGIN_PASS = "email_pw"
EMAIL_HOST = "host.yourdomain.com"
EMAIL_FROM = "Cistern <from@yourdomain.com>"
EMAIL_TO = "you@yourdomain.com"
EMAIL_SMS_TO = "smsemail@providerdomain"
